### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jhave21** [matkuki/ExCo#18]
Hi I would like to ask for another feature. 
I don't know what's it's called but, the feature I wanna ask is something like this:
when I highlight a word in the text editor, I would like all of the same words would be highlighted too.

Thanks.

**Comment by matkuki** [comment]
Hi @jhave21 ,
You mean with like the **highlight (Ctrl+G)** function, but automatically every time you select a word or a piece of text?
Will do!

**Comment by matkuki** [comment]
@jhave21 ,
Added a test version of the highlight functionality. It's not completely identical to the Notepad++ version as it also highlights matches inside strings, not just independent words.

Try it and give me your thoughts.
