### ISSUE TITLE
Awk lexer

### ISSUE THREAD

**Issue by svnpenn** [matkuki/ExCo#19]
please and thank you

**Comment by matkuki** [comment]
Will do.

**Comment by matkuki** [comment]
Added.
I am not familiar with AWK, so I added the keywords, builtin variables and builtin functions from this page:
http://pubs.opengroup.org/onlinepubs/7908799/xcu/awk.html
If there are other keywords or builtins that need to be included, let me know.

Please test it and tell me if there are any problems.

**Comment by svnpenn** [comment]
thanks

it should be fine - but the version you linked is 20 years old - here is current version

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html

**Comment by matkuki** [comment]
Thanks for the update.
I Noticed that I still need to add the *Environment Variables*. Will add them in a moment.

**Comment by matkuki** [comment]
No, my mistake. 
The Environment Variables only affect AWK's execution, they are not keywords.

**Comment by matkuki** [comment]
I am closing this. If there are bugs, please let me know.
