### ISSUE TITLE
Can't open zips for Windows binaries of the editor

### ISSUE THREAD

**Issue by WDBell** [matkuki/ExCo#2]
Their names are ExCo_Windows_x64.zip and ExCo_Windows_x86.zip.

Your product looks very nice and I would like to try it.

**Comment by matkuki** [comment]
Hi WDBell,

**first method (assuming you're using the FireFox browser)**:
- go to https://github.com/matkuki/ExCo-Windows-Compiled
- select which version you want to use (x86 or x64) by clicking on it:
![1](https://cloud.githubusercontent.com/assets/10289651/17604937/52d4aae6-6018-11e6-80d3-65824f38f579.jpg)

- right click on ```View Raw``` and select ```Save link as ...``` and save it to your computer:
![2](https://cloud.githubusercontent.com/assets/10289651/17605018/b3a7dd8e-6018-11e6-8cf7-c8578a68bcc2.jpg)
- then unzip it and run ```ExCo.exe```
<br><br><br>

**second method**:
- go to https://github.com/matkuki/ExCo-Windows-Compiled
- click on the ```Clone or download``` then select ```Download ZIP``` and save it to your computer:
![3](https://cloud.githubusercontent.com/assets/10289651/17605273/e73b9edc-6019-11e6-8796-418981a8a444.jpg)
- then unzip ```ExCo-Windows-Compiled-master.zip```, then again unzip the version you wish to use and run ```ExCo.exe```
<br><br><br>

Tell me if it works,
Matic

**Comment by WDBell** [comment]
Hi Matic,

Thank you for responding. Incredibly stupid of me! I appreciate your 
patience. It works and looks great.

Bill

**Comment by matkuki** [comment]
No problem Bill, glad to help.
