### ISSUE TITLE
Word wrap?

### ISSUE THREAD

**Issue by Prooffreader** [matkuki/ExCo#3]
Is it possible to word-wrap lines?

**Comment by matkuki** [comment]
Of course you can @Proofreader, just write this in the REPL:
``` cmain.setWrapMode(PyQt4.Qsci.QsciScintilla.WrapWord) ```
There are four wrap modes:
```
PyQt4.Qsci.QsciScintilla.WrapNone - Lines are not wrapped.
PyQt4.Qsci.QsciScintilla.WrapWord - Lines are wrapped at word boundaries.
PyQt4.Qsci.QsciScintilla.WrapCharacter - Lines are wrapped at character boundaries.
PyQt4.Qsci.QsciScintilla.WrapWhitespace - Lines are wrapped at whitespace boundaries. 
```
Here is a screenshot of how to set it up:

![temp](https://cloud.githubusercontent.com/assets/10289651/18280714/53b1126e-745a-11e6-95c6-5210ff5639af.jpg)
Substitute ```cmain``` with ```cupper``` or ```clower``` acording to which window you have the document in.

Tell me if you have any trouble.

Matic

**Comment by matkuki** [comment]
Hey @Prooffreader ,

Just added word wrapping. It's accessible with ```Ctrl+P``` or in the menubar
```Advanced->Enable/Disable Line Wrapping``` or using the function wheel (F1).
