### ISSUE TITLE
Go to tab right/left

### ISSUE THREAD

**Issue by novakpetrovic** [matkuki/ExCo#31]
Hi,

I just came across your very cool project. A couple of questions:

- Is there a go to tab right/left function (and shortcut) in ExCo (as opposed to moving a tab right/left)?
- If there isn't such a feature, do you support adding it?

Kind regards
Novak

**Comment by matkuki** [comment]
Done. **Ctrl+,**/**Ctrl+.** now select left/right, while **Ctrl+Shift+,**/**Ctrl+Shift+.** now have the old functionality of moving tabs left/right.

Thanks for pointing this out. Weird that I always use the mouse to select tabs
