### ISSUE TITLE
QsciLexerCustom fold code by indent or keyword

### ISSUE THREAD

**Issue by Mr-ZBin** [matkuki/ExCo#32]
Dear Developer,
I'm a SAS program in a CRO company. I created an editor about SAS language in my spare time, and I created a class QsciLexerSAS which inherit QsciLexerCustom to highlight the  word in the editor through learn about your Excillent code, and my editor works very well. 

#**My question** is about how to fold the code by myself, and I did't find any reference resources. If you have any suggestions, could you mind tell me? Thank you very much.
**What's SAS:** [https://en.wikipedia.org/wiki/SAS_(software)](url) #

**Comment by matkuki** [comment]
Look at this and you should get the idea:
https://github.com/matkuki/qscintilla_docs/blob/master/examples/folding.py

There is also other examples in there, in case you are interested.
And we have a website for QScintilla: https://qscintilla.com

**Comment by Mr-ZBin** [comment]
Thank you so much, it's very useful. Your excellent will help more people. Thanks again
