### ISSUE TITLE
Advanced function Autocompletion Questions

### ISSUE THREAD

**Issue by stduinocom** [matkuki/ExCo#34]
Hello,Happy to learn from the code examples you provided, but I now have a functional problem with automatic case completion ignoring. By running the program You provided EX.CO. 6.13, I enable the function of autocompletion, but when I actually typed in the text, I found that when I typed in INT and then lowercase i, the prompt for iNT would appear, that means I in INT is replaced by i.This is not the automatic completion case ignore I want, how do I achieve this function, look forward to your tips and advice. Thank you very much.

**Comment by matkuki** [comment]
Hey @stduinocom 
Updated the autocompletion code to work as you described. But this is for the source code version only, do you need an executable version? Then I would need to create a new release.

Also the behaviour not matches the case of the first found word, example:
If you have `INT` and `int` both in your document, whichever comes first in the document will be matched.

**Comment by stduinocom** [comment]
Glad to hear from you, you don't have to generate an executable file . Can you tell me how to do this, I only use this setting but can't do what i want now.
#setAutoCompletionCaseSensitivity(False) 
 Thank you again.
