### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [matkuki/ExCo#36]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D1%8B-%D0%BA%D0%BE%D0%B4%D0%B0/ex-co.html).

The project is interesting, so please don't abandon it!

The only question is how to run a python script directly from the editor?

**Comment by matkuki** [comment]
Hello @mrkaban ,
Thank you very much for the kind words,  and support.
It will not be abandoned, no worries, as I use it for work every day,

The way a `script from a file` can currently be run is in the `REPL` using: `run_command("python path/to/my_script.py")` or the shorthand `rc: python path/to/my_script.py`. But that uses the system's `Python` interpreter, are you asking for a way to run a script with `ExCo`'s  python? That can be added as a built-in function if needed.

But if you just need to run code, `Ctrl+5` brings up the `multiline REPL`, paste the code in and press `Return` (the small `Enter` on the right of the arrow keys). Note that some `built-in`'s functions are overridden, like `open`, `print`, ... For example, to print a message to the `REPL MESSAGES` window use the `echo` function.

Example:
![image](https://user-images.githubusercontent.com/10289651/95673953-4c29fd00-0bad-11eb-8c15-a76bb1a914c6.png)

This could probably be improved, as discoverability of the `Multiline REPL` is not that obvious. If you have any suggestions, let me know.
