### ISSUE TITLE
drag file from directory tree to desktop or local folder

### ISSUE THREAD

**Issue by Mr-ZBin** [matkuki/ExCo#37]
Hi,
Thanks for your wonderful work, and I made a similar file/directory tree explorer with yours.
Could you mind adding a new function that we can drag file or folder from directory tree to desktop or other local folder? 
I search the solution many days to solve this issue, but don't have any useful information about dragMoveEvent, dragEnterEvent or dragLeaveEvent.
Thank you.

![screenshot](https://user-images.githubusercontent.com/22544491/99025128-152b7a80-25a3-11eb-9607-29231447fc93.gif)

**Comment by matkuki** [comment]
@Mr-ZBin Thank you.

Here is a simple example: [drag_drop_file_example.zip](https://github.com/matkuki/ExCo/files/5540605/drag_drop_file_example.zip)
Run it, press and drag the `Export` button to a Windows Explorer or Desktop and it will copy file `test.txt` to it
You need `PyQt` version `5.15.0` or above!

**Comment by Mr-ZBin** [comment]
@matkuki Thank you so much.

I did some changes from your code to my project, and it works well. It is not that you pressed a button, instead of overwrite startDrag() method. Because I have to use pressed signal to implement other functionality. The MimeData class you provided is difficult for me.
I'm a sas programmer, mainly engaged in the development of sas macro. And I'm very interested in python and qt but not good at it. Thanks for your help and wonderful ExCo project again.
Here is my change:
[drag_file_from_qtreewidget.zip](https://github.com/matkuki/ExCo/files/5541866/drag_file_from_qtreewidget.zip)
