### ISSUE TITLE
Add eC (Ecere C) syntax highlighting and code tree displaying for D, eC and Pascal

### ISSUE THREAD

**Issue by den32ds** [matkuki/ExCo#38]
Thanks for this awesome editor, but I am missing these things

**Comment by matkuki** [comment]
Thanks.
Will try to add these features as soon as possible.

**Comment by matkuki** [comment]
Hi @den32ds ,
added D and Pascal code tree displaying, but I have no experience with Ecere C. Is there a tool for parsing Ecere C code?

Also I don't know of how exactly does Ecere C syntax works so I could add syntax highlighting, is there documentation for it?

**Comment by rellikmil** [comment]
@matkuki sorry for delay (yep)
I think this can help you with eC - https://ecere.com/tao.pdf
