### ISSUE TITLE
Cannot open ExCo.exe on version 6.15

### ISSUE THREAD

**Issue by Mr-ZBin** [matkuki/ExCo#42]
When I downloaded latest version 6.15 and open ExCo.exe, it showed below message:

![微信截图_20210326145222](https://user-images.githubusercontent.com/22544491/112594420-dd331e80-8e43-11eb-8a2f-3dd6441bc063.png)

**Comment by matkuki** [comment]
@Mr-ZBin 
Sorry for the delay, will try to fix it immediately!

**Comment by matkuki** [comment]
@Mr-ZBin 
Thanks again for the report!
I updated the archive. Can you try again please?

**Comment by Mr-ZBin** [comment]
Hi @matkuki,

I don't find the latest release version as below. Could you update frozen_exco_windows_64bit.7z? And then I'll try it again. Thank you very much.

![image](https://user-images.githubusercontent.com/22544491/113110753-0388fd80-923a-11eb-8dfa-a6e1e7d4f8b0.png)

**Comment by Mr-ZBin** [comment]
@matkuki 
It works well now.
