### ISSUE TITLE
QPoint Error

### ISSUE THREAD

**Issue by CR7PorInd** [matkuki/ExCo#43]
I want to test this app.
It shows: 
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'

**Comment by matkuki** [comment]
Hey @CR7PorInd ,

Can you tell me how are you running the app and your system specification? Windows or Linux, PyQt version, ...?

**Comment by matkuki** [comment]
If you have more questions, feel free to post them here.

**Comment by CR7PorInd** [comment]
> Hey @CR7PorInd ,
> 
> Can you tell me how are you running the app and your system specification? Windows or Linux, PyQt version, ...?

PyQt5 5.15.6
macOS Monterey 12.0.1
Python 3.10
Everything looks great but to QPoint, you must pass on int values. Anyway, I edited your code (only for myself) and made it an integer. But anyway, I am also making an IDE on QScintilla. It has 10 supported lexers, autocompletion (For Python), running all programs. All the very best. I am making a new app collection. I might add your app to my collection. It is very good.
