### ISSUE TITLE
QPoint Error

### ISSUE THREAD

**Issue by CR7PorInd** [matkuki/ExCo#44]
PyQt5 5.15.6
macOS Monterey 12.0.1
Python 3.10

TypeError: arguments did not match any overloaded call:
```python

QPoint(): too many arguments
QPoint(int, int): argument 1 has unexpected type 'float'
QPoint(QPoint): argument 1 has an unexpected type 'float'
```

Everything looks great but to QPoint, you must pass on int values. 
Anyway, I edited your code (only for myself) and made it an integer. I am also making an IDE on QScintilla. It has 10 supported lexers, autocompletion (For Python), running all programs. I am making a new app collection.
It has 6 apps (including the IDE I created). Browser, Camera, Audio Converter, Online Public Chat Group, IDE, and Word-like Text Editor.

I might add your app to my collection if you add features to show docs, call tips and run many languages.

All the very best.

**Comment by matkuki** [comment]
Fixed
