### ISSUE TITLE
ExCo: The application failed to start because no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by ghost** [matkuki/ExCo#48]
Reinstalling the application might fix this problem.

Available platform plugins are: minimal, offscreen, windows.

This is what the error message said. I'm on Windows 7. Does it require Windows 10+?

**Comment by matkuki** [comment]
Hi, it should work on Windows 7, so it's probably a packaging error. Thanks for reporting 👍
Will notify you when it's fixed.

**Comment by matkuki** [comment]
@ghost, I have repackaged with PyQt5, can you try downloading and executing it again?

**Comment by hgntn** [comment]
I also have Windows 7 and confirmed it's running now. Also tested on Windows 8.1

**Comment by matkuki** [comment]
Thanks 👍
