### ISSUE TITLE
ExCo fails to run - error "AttributeError: module 'components' has no attribute 'fonts'"

### ISSUE THREAD

**Issue by skilleter** [matkuki/ExCo#60]
As per the `INSTRUCTIONS.md` file, running ExCo from the `master` branch on Ubuntu 22.04.01 using Python 3.10.6 fails immediately with an error:

```
$ python3 main.py 
Traceback (most recent call last):
  File "/home/jms/SourceCode/open-source/ExCo/main.py", line 137, in <module>
    main()
  File "/home/jms/SourceCode/open-source/ExCo/main.py", line 120, in main
    components.fonts.set_application_font(
AttributeError: module 'components' has no attribute 'fonts'
```

Tested from tip of `master` branch and also tested using `v7.2` tag with same result.

Also tested, with same result, using a virtual environment with the following `requirements.txt` file:

```
PyQt5
Qscintilla
psutil
```

Running `exco.py` instead works - I suspect that the instructions are out of date and that the `main.py` file is redundant.

**Comment by matkuki** [comment]
Absolutely correct, thank you for checking!
Removed the unused `main.py` file and updated the instructions with 36f1300905cf80ad68f76eebefa8961b58fc7ea9
