### ISSUE TITLE
First run fails due to missing .exco folder

### ISSUE THREAD

**Issue by shaolo1** [matkuki/ExCo#61]
Not sure where the .exco folder is normally created, but a similar exist check and a mkdir before the file open would fix this.

(venv) $ python ExCo-7.3/exco.py 
Traceback (most recent call last):
  File "/home/foo/exco/ExCo-7.3/exco.py", line 173, in <module>
    main()
  File "/home/foo/exco/ExCo-7.3/exco.py", line 131, in main
    number_of_instances = components.processcontroller.check_opened_excos()
  File "/home/foo/exco/ExCo-7.3/components/processcontroller.py", line 45, in check_opened_excos
    with open(PID_FILE, "w+", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/foo/.exco/pid_list.txt'

**Comment by matkuki** [comment]
Uh, thanks for reporting! Will start fixing it now ...

**Comment by matkuki** [comment]
Commit https://github.com/matkuki/ExCo/commit/1dafc3c6e41da6f86904c2a4fba083678287fc17 fixes this. Can you try it again now, please?

**Comment by shaolo1** [comment]
Yes.  Thanks.  That fixed it.  When I manually created the directory before it prompted "Do you wish to generate the default user definition and function file?  Yes No".  That prompt no longer appears (not sure if you meant to change that).

**Comment by matkuki** [comment]
Thank you for reporting the issue.

>  When I manually created the directory before it prompted "Do you wish to generate the default user definition and function file? Yes No". That prompt no longer appears (not sure if you meant to change that).

I removed that prompt, now the file is automatically generated, it's the `~/.exco/userfunctions.cfg` file, where the user's custom settings and functions can be added. For example: if you wish to call the following function from the `ExCo` `REPL`
```python
def hello():
    echo("Hello from ExCo")
```
... add it to the `~/.exco/userfunctions.cfg` file and reload `ExCo` or go to `File > Reload User Definitions`:
![image](https://user-images.githubusercontent.com/10289651/218265790-f1034a85-9ae6-48e5-87cd-4557180c51a4.png)
... then you can run the function in `ExCo`'s `REPL` with `"hello()" + Enter`.
