### ISSUE TITLE
Crash with menu item "System | Show current working directory explorer Alt+F7"

### ISSUE THREAD

**Issue by shaolo1** [matkuki/ExCo#62]
$ python ExCo-master/exco.py 
Traceback (most recent call last):
  File "/home/foo/exco/ExCo-master/gui/mainwindow.py", line 1847, in show_explorer
    self.system.show_explorer()
  File "/home/foo/exco/ExCo-master/gui/mainwindow.py", line 4232, in show_explorer
    self._parent.display.display_warning("Unimplemented yet!")
AttributeError: 'Display' object has no attribute 'display_warning'. Did you mean: 'repl_display_warning'?
Aborted (core dumped)

**Comment by matkuki** [comment]
Thanks for testing, will fix the error and add the Linux functionality for `Alt+F7` now ...

**Comment by matkuki** [comment]
Commit https://github.com/matkuki/ExCo/commit/c43a7aa693db7860603d620439ae8131bdd3a4de should fix the error and add the functionality for `Alt+F7`. Can you test it now, please?

And thanks again for testing `ExCo` 👍👍

**Comment by shaolo1** [comment]
It no longer crashes, but doesn't appear to do anything.  No window opens.

**Comment by matkuki** [comment]
If you run the command `xdg-open ~/` in a console, does your home directory open in you default explorer?

**Comment by shaolo1** [comment]
Yes

**Comment by matkuki** [comment]
Got it! Pushed a fix. Can you test it now, please?

**Comment by shaolo1** [comment]
Yes.  That worked.
