### ISSUE TITLE
Add SmallBASIC lexer

### ISSUE THREAD

**Issue by ghost** [matkuki/ExCo#68]
References:

https://github.com/Joe7M/smallbasic.atom.syntaxcoloring

https://github.com/Joe7M/smallbasic.geany.syntaxcoloring

https://github.com/Joe7M/smallbasic.vscode.syntaxcoloring

**Comment by matkuki** [comment]
`SmallBASIC` added with: https://github.com/matkuki/ExCo/commit/88ebb29162bcea51e9a464c995e2775f94843c7a
