### ISSUE TITLE
如何打包？

### ISSUE THREAD

**Issue by 17Reset** [matkuki/ExCo#69]
Hello, I would like to ask you how to package this project into a directory executable and compile the python source code into a pyx file to prevent the code from being exposed?

**Comment by matkuki** [comment]
Hi.
The only way I know of compiling `Python` modules into actual binaries is using `Cython`. You have to compile all `.py` files with `Cython` one-by-one, which will give you `.pyd` files (that are actually dynamic shared libraries with a different extension), then use `cx_freeze` to package the application. A `cx_freeze` freeze script is already available in `utilities` subdirectory: `utilities/freeze_exco.py`.

But compiling all the `.py` files into a **working** single executable is unknown to me. [Nuitka](https://nuitka.net/) supposedly can do this, but it has issues with `PyQt` and portability across computers.
If you manage to find any more information on a working procedure to compile to a single executable, please let me know.
