### ISSUE TITLE
Please add Lisp/SKILL(Cadence) lexer

### ISSUE THREAD

**Issue by jianlinwei** [matkuki/ExCo#70]
Could you support Lisp/SKILL(Cadence) lexer ?
Thanks

**Comment by matkuki** [comment]
Added the lexer.

Currently, all built-in functions are highlighted the same, if you wish the function
categories to be highlighted differently, please give me a grouping list of them.

I used this document to get the language information: https://cpb-us-w2.wpmucdn.com/sites.gatech.edu/dist/0/367/files/2016/03/Intro_to_skill_prog.pdf

This was my test code:
```lisp
signalList = '(
( nil strength 1.5 )
( nil strength 0.4 )
( nil strength 2.5 )
)

sort( signalList
'lambda( ( a b ) a->strength <= b->strength )
)

procedure( trAdd( x y )
printf( "Adding %d and %d … %d \n" x y x+y )
x+y
) => trAdd
```
