### ISSUE TITLE
is there a debugger for some of the coding langs??

### ISSUE THREAD

**Issue by SimonDev666** [matkuki/ExCo#74]
could not see anything about a debugger - may have missed it
if there is not, is it on your future ehancements list??

**Comment by matkuki** [comment]
Interesting suggestion.
Currently `ExCo` is made as an editor base, with the ability to upgrade it to whatever you need.
There is a working example of a `C/C++` debugger added to it ( uses `GDB` but is not `open-source`): https://embeetle.com

Which languages are you interested in for debugging?
