### ISSUE TITLE
is there a user manual?

### ISSUE THREAD

**Issue by andrewchenshx** [matkuki/ExCo#76]
it's a great app i've been searching for a longtime.
is there a user manual?
it would be better if i could be found under the help menu.
thanks

**Comment by matkuki** [comment]
Hey @andrewchenshx 

Interesting, this is the first time anyone asked for a manual.
I think the base functionality is quite easy to undestand, it's similar to Notepad++, Notepad Next, ...

The **"Advanced"** features would probably be:
- Python built-in: you can run any Python code in the `REPL` at the bottom of the screen, to for example:
  - Manipulate text of any editor (but you have to know how the QScintilla editing component works in Python)
  - Do any other Python stuff you desire
- Text diffing: select a document, then to diff it, right click on the tab you want to diff to
- File explorer (`Ctrl+F7` or menubar "System > Show current working directory in tree explorer"): a `Total Commander` like file explorer, it also has a  variant (`F7`)
- Code explorer (`F8` or menubar `Advanced > Create/reload node tree`): Shows the parsed code of the currently selected editor in a tree-like structure, depending on the programming language of the file that's opened in the editor
- Integrated terminal (menubar `System > Show terminal emulator`): a cross-platform terminal emulator 
- There's probably, but that's off the top of my head ...

If you want specifics on any item or maybe on something else, please let me now.
